spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coworking
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        show_sql: false
        format_sql: true

  flyway:
    enabled: true

integration:
  payment-gateway:
    url: http://wiremock:8080/api/payments/process