CREATE TABLE "user"
(
    ID         BIGINT,

    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME  VARCHAR(100) NOT NULL,
    EMAIL      VARCHAR(150) NOT NULL,
    PASSWORD   VARCHAR(255) NOT NULL,
    ROLE       VARCHAR(20)  NOT NULL,
    ENABLED    BOOLEAN      NOT NULL,

    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL,
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP,

    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USER_ROLE CHECK (ROLE IN ('ADMIN', 'USER'))
);

CREATE INDEX IDX_USER_EMAIL ON "user" (EMAIL);