CREATE TABLE SPACE
(
    ID          BIGINT,

    NAME        VARCHAR(150)   NOT NULL,
    TYPE        VARCHAR(30)    NOT NULL,
    HOURLY_RATE NUMERIC(10, 2) NOT NULL,

    CREATED_BY  VARCHAR(100)   NOT NULL,
    CREATED_AT  TIMESTAMP      NOT NULL,
    UPDATED_BY  VARCHAR(100),
    UPDATED_AT  TIMESTAMP,

    CONSTRAINT PK_SPACE PRIMARY KEY (ID),
    CONSTRAINT CK_SPACE_TYPE CHECK ( TYPE IN ('DESK', 'MEETING_ROOM', 'AUDITORIUM') ),
    CONSTRAINT CK_SPACE_HOURLY_RATE CHECK ( HOURLY_RATE > 0 )
);

CREATE INDEX IDX_SPACE_TYPE ON SPACE (TYPE);