CREATE TABLE RESERVATION
(
    ID             BIGINT,

    USER_ID        BIGINT        NOT NULL,
    SPACE_ID       BIGINT        NOT NULL,
    START_TIME     TIMESTAMP      NOT NULL,
    END_TIME       TIMESTAMP      NOT NULL,
    STATUS         VARCHAR(30)    NOT NULL,
    PAYMENT_METHOD VARCHAR(30)    NOT NULL,
    TOTAL_PRICE    NUMERIC(10, 2) NOT NULL,

    CREATED_BY     VARCHAR(100)   NOT NULL,
    CREATED_AT     TIMESTAMP      NOT NULL,
    UPDATED_BY     VARCHAR(100),
    UPDATED_AT     TIMESTAMP,

    CONSTRAINT PK_RESERVATION PRIMARY KEY (ID),
    CONSTRAINT FK_RESERVATION_USER FOREIGN KEY (USER_ID) REFERENCES "user" (ID),
    CONSTRAINT FK_RESERVATION_SPACE FOREIGN KEY (SPACE_ID) REFERENCES SPACE (ID),
    CONSTRAINT CK_RESERVATION_START_TIME CHECK ( START_TIME > CURRENT_TIMESTAMP ),
    CONSTRAINT CK_RESERVATION_DATE_RANGE CHECK ( END_TIME > START_TIME ),
    CONSTRAINT CK_RESERVATION_PAYMENT_METHOD CHECK ( PAYMENT_METHOD IN ('CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER') ),
    CONSTRAINT CK_RESERVATION_STATUS CHECK ( STATUS IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') )
);

CREATE INDEX IDX_RESERVATION_USER ON RESERVATION (USER_ID);
CREATE INDEX IDX_RESERVATION_DATE_RANGE ON RESERVATION (SPACE_ID, START_TIME, END_TIME);